---
postgresql:
  host: "your_postgresql_host"
  port: "your_postgresql_port"
  username: "your_postgresql_username"
  password: "your_postgresql_password"
  database: "your_postgresql_database"

http:
  ip: "your_http_ip"
  port: "your_http_port"

email: 
  email_sender_name: "your_email_sender_name"
  email_sender_address: "your_email_sender_address"
  email_sender_password: "your_email_sender_password"
  smtp_auth_address: "your_smtp_auth_address"
  smtp_server_address: "your_smtp_server_address"

jwt_secret: "your_jwt_secret"
