version: "3.9"

volumes:
  db-data:
  api:

services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=test_reminder
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - ./db-data:/var/lib/postgresql/data

#  app:
#    container_name: reminder-api
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#    restart: on-failure
#    volumes:
#      - api:/usr/src/app/



