version: "3.9"

volumes:
  db-data:
  api:

services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=reminder
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - ./db-data:/var/lib/postgresql/data
       # copy the sql script to create tables
#        - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reminder-reminder
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=reminder
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
    ports:
      - "8000:8000"
    depends_on:
      - db



