version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=reminder
    ports:
      - "5432:5432"

  reminder-api:
    container_name: reminder-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=reminder
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      - postgres
