version: '3.9'

networks:
  reminder_test:
    driver: bridge
volumes:
  dbtest-data:

services:
  app_tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - $PWD:/app
    depends_on:
      - db
    networks:
      -  reminder_test

  db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=test_reminder
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: on-failure
    networks:
      - reminder_test
    volumes:
      - ./dbtest-data:/var/lib/postgresql/data
